---
# handlers file for ansible-role-influxdb

- name: reload influxdb
  service:
    name: "{{ influxdb_service_name }}"
    state: reloaded

- name: restart influxdb
  service:
    name: "{{ influxdb_service_name }}"
    state: restarted

